# service configuration for our database
database:

  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: postgres:9.4.5

  # persist the database between containers by storing it in a volume
  volumes:
    - postgres-volume:/var/lib/postgresql/data

# service configuration for our dockerized Rails app
app:

  # use the Dockerfile next to this file
  build: .

  # makes the app container aware of the DB container
  links:
    - database

  # expose the port we configured Unicorn to bind to
  ports:
    - "80:3001"
  # map our application source code, in full, to the application root of our container
  volumes:
    - apache-volume:/home/pormibarrio

  environment:
    
    - PATH='/home/pormibarrio/bin:/home/pormibarrio/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'

    - PERL5LIB='/home/pormibarrio/perllib:/home/pormibarrio/commonlib/perllib:/home/pormibarrio/local/lib/perl5'

    - PERL_LOCAL_LIB_ROOT='/home/pormibarrio/local'

    - PERL_MB_OPT='--install_base "/home/pormibarrio/local"'

    - PERL_MM_OPT='INSTALL_BASE=/home/pormibarrio/local'

    #- PS1="(fms) $PS1"

